# action.yml
name: 'build-fuzzers'
description: "Builds an OSS-Fuzz project's fuzzers."
inputs:
  project-name:
    description: 'Name of the corresponding OSS-Fuzz project.'
    required: true
  fuzz-time:
    description: 'The time total allotted time for fuzzing in seconds.'
    requried: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PROJECT_NAME: ${{ inputs.project-name }}
    FUZZ_TIME: ${{ inputs.fuzz-time }}
